baseurl = "https://priscillakyeibaffour.github.io"
metaDataFormat = "yaml"
title = "Blist Multilingual Theme"
theme = "blist"
publishDir = "../../../docs"
themesDir = "../.."


DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Great Love Basic School"
      introSubtitle = "Kumasi"
      introPhoto = "/featured-placeholder.jpg"
      logo = "/blist-logo.png"

    [[languages.en.menu.main]]
        name = "Home"
        url = "/en/blog/history/"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/history/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Contact"
        url = "/en/blog/history/"
        weight = 5

    [[languages.en.menu.main]]
        name = "Events"
        url = "/en/blog/history/"
        weight = 6

    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 7

    [[languages.en.menu.main]]
        name = "Courses"
        url = "/en/blog/history/"
        weight = 8

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - Great Love Basic School · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

[params.homepage.social]
  # Global params common for both languages
  title = "Follow us"
  description = "We are available on the following social media platforms"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
